import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// ⭐ THÊM MENU
import HamburgerMenu from "@/components/HamburgerMenu";

// ⭐ GIỮ PAGE TRANSITION (CHỈ LÀ HIỆU ỨNG)
import PageTransition from "@/components/PageTransition";

// ⭐ GIỮ AIBUBBLE
import AIBubble from "@/components/AIBubble";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        {/* ⭐ NỀN ĐỘNG NHẸ NHÀNG */}
        <div className="fixed inset-0 -z-50 bg-[url('/bg.webp')] bg-cover bg-center opacity-[0.09] animate-bg-pan" />

        {/* ⭐ GIỮ PAGE TRANSITION */}
        <PageTransition />

        {/* ⭐ HEADER MENU CỐ ĐỊNH */}
        <header className="w-full flex justify-end p-4 fixed top-0 right-0 z-50">
          <HamburgerMenu />
        </header>

        {/* ⭐ GIỮ PADDING TOP */}
        <div className="pt-14">
          {children}
        </div>

        {/* ⭐ GIỮ AIBUBBLE */}
        <AIBubble />

      </body>
    </html>
  );
}