import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// ⭐ THÊM MENU
import HamburgerMenu from "@/components/HamburgerMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ⭐ HEADER CỐ ĐỊNH CHO MENU */}
        <header className="w-full flex justify-end p-4 fixed top-0 right-0 z-50">
          <HamburgerMenu />
        </header>

        {/* ⭐ PADDING TOP ĐỂ KHỎI CHE NỘI DUNG */}
        <div className="pt-14">
          {children}
        </div>
      </body>
    </html>
  );
}